POST http://localhost:8080/customers
Content-Type: application/json

{
  "costumerDto":{
    "phone":"1111-11-11",
    "email":"e@gmail.com"
  },
  "products":[
    {
      "productTitle":"product1",
      "price":100
    },
    {
      "productTitle":"product2",
      "price":200
    }
  ]
}